export const DEFINIR_FUNCIONARIOS = "DEFINIR_FUNCIONARIOS";
export const DEFINIR_UM_FUNCIONARIO = "DEFINIR_UM_FUNCIONARIO";
export const CRIAR_FUNCIONARIO = "CRIAR_FUNCIONARIO";
export const ATUALIZAR_FUNCIONARIO = "ATUALIZAR_FUNCIONARIO";
export const DELETAR_FUNCIONARIO = "DELETAR_FUNCIONARIO";
export const LIMPAR_LISTA_FUNCIONARIO = "LIMPAR_LISTA_FUNCIONARIO";

export const DEFINIR_DEPARTAMENTOS = "DEFINIR_DEPARTAMENTOS";
export const DEFINIR_UM_DEPARTAMENTO = "DEFINE_UM_DEPARTAMENTO";
export const CRIAR_DEPARTAMENTO = "CRIAR_DEPARTAMENTO";
export const ATUALIZAR_DEPARTAMENTO = "ATUALIZA_DEPARTAMENTO";
export const DELETAR_DEPARTAMENTO = "DELETA_DEPARTAMENTO";
export const LIMPAR_LISTA_DEPARTAMENTO = "LIMPA_LISTA_DEPARTAMENTO";

export const DEFINIR_MOTIVOS = "DEFINIR_MOTIVOS";
export const DEFINIR_UM_MOTIVO = "DEFINIR_UM_MOTIVO";
export const CRIAR_MOTIVO = "CRIAR_MOTIVO";
export const ATUALIZAR_MOTIVO = "ATUALIZAR_MOTIVO";
export const DELETAR_MOTIVO = "DELETAR_MOTIVO";
export const LIMPAR_LISTA_MOTIVO = "LIMPAR_LISTA_MOTIVO";

export const DEFINIR_REGISTROS = "DEFINIR_REGISTROS";
export const DEFINIR_UM_REGISTRO = "DEFINIR_UM_REGISTRO";
export const CRIAR_REGISTRO = "CRIAR_REGISTRO";
export const ATUALIZAR_REGISTRO = "ATUALIZAR_REGISTRO";
export const DELETAR_REGISTRO = "DELETAR_REGISTRO";
export const LIMPAR_LISTA_REGISTRO = "LIMPAR_LISTA_REGISTRO";

export const DEFINIR_CATEGORIES = "DEFINIR_CATEGORIES";
export const DEFINIR_CATEGORY = "DEFINIR_CATEGORY";
export const CRIAR_CATEGORY = "CRIAR_CATEGORY";
export const ATUALIZAR_CATEGORY = "ATUALIZAR_CATEGORY";
export const DELETAR_CATEGORY = "DELETAR_CATEGORY";
export const LIMPAR_LISTA_CATEGORY = "LIMPAR_LISTA_CATEGORY";

export const DEFINIR_CORES = "DEFINIR_CORES";
export const DEFINIR_COR = "DEFINIR_COR";
export const CRIAR_COR = "CRIAR_COR";
export const ATUALIZAR_COR = "ATUALIZAR_COR";
export const DELETAR_COR = "DELETAR_COR";
export const LIMPAR_LISTA_COR = "LIMPAR_LISTA_COR";

export const DEFINIR_ITEMS = "DEFINIR_ITEMS";
export const DEFINIR_ITEM = "DEFINIR_ITEM";
export const CRIAR_ITEM = "CRIAR_ITEM";
export const ATUALIZAR_ITEM = "ATUALIZAR_ITEM";
export const DELETAR_ITEM = "DELETAR_ITEM";
export const LIMPAR_LISTA_ITEM = "LIMPAR_LISTA_ITEM";

export const DEFINIR_TYPEMOVEMENTS = "DEFINIR_TYPEMOVEMENTS";
export const DEFINIR_TYPEMOVEMENT = "DEFINIR_TYPEMOVEMENT";
export const CRIAR_TYPEMOVEMENT = "CRIAR_TYPEMOVEMENT";
export const ATUALIZAR_TYPEMOVEMENT = "ATUALIZAR_TYPEMOVEMENT";
export const DELETAR_TYPEMOVEMENT = "DELETAR_TYPEMOVEMENT";
export const LIMPAR_LISTA_TYPEMOVEMENT = "LIMPAR_LISTA_TYPEMOVEMENT";

export const NOTIFICAR = "NOTIFICAR";
