export const DEFINE_FUNCIONARIOS = "DEFINE_FUNCIONARIOS";
export const DEFINE_UM_FUNCIONARIO = "DEFINE_UM_FUNCIONARIO";
export const CRIA_FUNCIONARIO = "CRIA_FUNCIONARIO";
export const ATUALIZA_FUNCIONARIO = "ATUALIZA_FUNCIONARIO";
export const DELETA_FUNCIONARIO = "DELETA_FUNCIONARIO";
export const LIMPA_LISTA_FUNCIONARIO = "LIMPA_LISTA_FUNCIONARIO";

export const DEFINE_DEPARTAMENTOS = "DEFINE_DEPARTAMENTOS";
export const DEFINE_UM_DEPARTAMENTO = "DEFINE_UM_DEPARTAMENTO";
export const CRIA_DEPARTAMENTO = "CRIA_DEPARTAMENTO";
export const ATUALIZA_DEPARTAMENTO = "ATUALIZA_DEPARTAMENTO";
export const DELETA_DEPARTAMENTO = "DELETA_DEPARTAMENTO";
export const LIMPA_LISTA_DEPARTAMENTO = "LIMPA_LISTA_DEPARTAMENTO";

export const DEFINE_MOTIVOS = "DEFINE_MOTIVOS";
export const DEFINE_UM_MOTIVO = "DEFINE_UM_MOTIVO";
export const ATUALIZA_MOTIVO = "ATUALIZA_MOTIVO";
export const DELETA_MOTIVO = "DELETA_MOTIVO";
export const LIMPA_LISTA_MOTIVO = "LIMPA_LISTA_MOTIVO";
export const CRIA_MOTIVO = "CRIA_MOTIVO";

export const DEFINE_REGISTROS = "DEFINE_REGISTROS";
export const DEFINE_UM_REGISTRO = "DEFINE_UM_REGISTRO";
export const ATUALIZA_REGISTRO = "ATUALIZA_REGISTRO";
export const DELETA_REGISTRO = "DELETA_REGISTRO";
export const LIMPA_LISTA_REGISTRO = "LIMPA_LISTA_REGISTRO";
export const CRIA_REGISTRO = "CRIA_REGISTRO";
